version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: root      
      MYSQL_DATABASE: my_database            
      MYSQL_USER: my_user                    
      MYSQL_PASSWORD: my_password           
    ports:
      - "3306:3306"                          
    volumes:
      - ./data:/var/lib/mysql                
    restart: always
